# Compiled from slate doc: calculator
# Generated by slate-code; do not edit by hand.

from typing import Callable, Dict

"""Tiny CLI calculator — read two numbers + one op, print the result."""

# Operations table is built once at import time so @apply_operation can
# look up the chosen op without an if/elif chain in every call.
OPS: Dict[str, Callable[[float, float], float]] = {}

# ─── prompt ───
# Prompt the user with the given string and re-prompt until they enter a parseable float. Returns the float.
def read_number(prompt):
    while True:
        try:
            return float(input(prompt))
        except ValueError:
            pass

# ─── prompt ───
# Use @read_number twice — once with prompt "Enter the first number: " and once with "Enter the second number: " — and return them as a tuple (a, b).
def read_two_numbers():
    a = read_number("Enter the first number: ")
    b = read_number("Enter the second number: ")
    return (a, b)

# ─── prompt ───
# Return a + b. Pure, no side effects.
def add(a, b):
    return a + b

# ─── prompt ───
# Return a - b. Pure, no side effects.
def subtract(a, b):
    return a - b

# ─── prompt ───
# Return a * b. Pure, no side effects.
def multiply(a, b):
    return a * b

# ─── prompt ───
# Return a / b. If b is zero, raise ZeroDivisionError("Cannot divide by zero") so the caller can handle it cleanly.
def divide(a, b):
    if b == 0:
        raise ZeroDivisionError("Cannot divide by zero")
    return a / b

# ─── prompt ───
# Populate the global OPS dict with mappings from operator strings to the matching function: "+" → @add, "-" → @subtract, "*" → @multiply, "/" → @divide. Idempotent — clear OPS before populating so calling twice is safe.
def register_ops():
    global OPS
    OPS = {}
    OPS["+"] = add
    OPS["-"] = subtract
    OPS["*"] = multiply
    OPS["/"] = divide

# ─── prompt ───
# Prompt the user (showing the keys of OPS sorted) until they enter one of the registered operators. Return the operator string.
def read_operator(OPS):
    while True:
        operator = input(f"Enter operator ({', '.join(sorted(OPS.keys()))}): ")
        if operator in OPS:
            return operator
        print("Invalid operator. Please try again.")

# ─── prompt ───
# Look the op up in OPS and apply it to (a, b). Raise KeyError with a clear message if the op is not registered.
def apply_operation(op, a, b):
    if op not in OPS:
        raise KeyError(f"Operation '{op}' is not registered")
    return OPS[op](a, b)

# ─── prompt ───
# Entry point. Call @register_ops, then read inputs via @read_two_numbers and @read_operator, then call @apply_operation. Print the formatted result. Catch ZeroDivisionError and print an error message instead of crashing.
def main():
    register_ops()
    try:
        a, b = read_two_numbers()
        op = read_operator(OPS)
        result = apply_operation(op, a, b)
        print(f"Result: {result}")
    except ZeroDivisionError:
        print("Error: Division by zero is not allowed.")
