# Compiled from slate doc: game
# Generated by slate-code; do not edit by hand.


def make_board() -> list[str]:
    """Return an empty 3x3 board as a flat list of 9 single-space strings."""
    return [' '] * 9

def render_board(board: list[str]) -> str:
    """Format `board` as a printable 3x3 grid with row separators."""
    rows = [' | '.join(board[i:i + 3]) for i in range(0, 9, 3)]
    return '\n---------\n'.join(rows)

def is_winning_line(board: list[str], line: tuple[int, int, int]) -> Optional[str]:
    """Return 'X' or 'O' if all three cells in `line` are non-empty and match. Else None."""
    a, b, c = line
    if board[a] != ' ' and board[a] == board[b] == board[c]:
        return board[a]
    return None

def check_winner(board: list[str]) -> Optional[str]:
    """Return 'X', 'O', 'draw', or None given the current @board.

    Walks every line in WINNING_LINES via @is_winning_line. If no winner and
    no empty cells remain, the game is a draw. Otherwise still in progress.
    """
    for line in WINNING_LINES:
        winner = is_winning_line(board, line)
        if winner is not None:
            return winner
    if ' ' not in board:
        return 'draw'
    return None

def valid_moves(board: list[str]) -> list[int]:
    """Return cell indices (0-8) that are still empty on `board`."""
    return [i for i, cell in enumerate(board) if cell == ' ']

def apply_move(board: list[str], index: int, player: str) -> list[str]:
    """Return a NEW board with `player` placed at `index`.

    Pure: does not mutate the input. Raises ValueError on illegal move
    (cell already occupied or index out of range).
    """
    if not 0 <= index < 9:
        raise ValueError(f"Index {index} out of range (must be 0-8)")
    if board[index] != ' ':
        raise ValueError(f"Cell {index} already taken by {board[index]!r}")
    new_board = list(board)
    new_board[index] = player
    return new_board

def current_player(board: list[str]) -> str:
    """X always plays first. Whoever has placed fewer marks plays next."""
    x_count = board.count('X')
    o_count = board.count('O')
    return 'X' if x_count <= o_count else 'O'

def ai_player_random(board: list[str]) -> int:
    """Pick a uniformly-random move from @valid_moves on the given @board."""
    moves = valid_moves(board)
    if not moves:
        raise ValueError("No valid moves; game is over")
    return random.choice(moves)

def human_player_input(board: list[str]) -> int:
    """Read a move (0-8) from stdin until the player provides a legal index.

    Reprompts on non-integer input and on cells that aren't currently in
    @valid_moves. Returns the chosen index.
    """
    legal = set(valid_moves(board))
    while True:
        raw = input(f"Your move (one of {sorted(legal)}): ")
        try:
            index = int(raw.strip())
        except ValueError:
            print(f"  '{raw}' is not an integer — try again.")
            continue
        if index not in legal:
            print(f"  Cell {index} is not available — try again.")
            continue
        return index

def play_one_game(human_plays: Optional[str] = None, verbose: bool = True) -> str:
    """Play a single game and return the result ('X', 'O', or 'draw').

    `human_plays`:
      - 'X' or 'O' → that side is controlled via @human_player_input
      - None       → both sides are @ai_player_random (good for smoke tests)

    Loop:
      1. Print the @render_board (if verbose).
      2. @check_winner — if decided, return.
      3. @current_player picks who's up.
      4. Their move comes from @human_player_input or @ai_player_random.
      5. @apply_move produces the next board; goto 1.
    """
    board = make_board()
    while True:
        if verbose:
            print(render_board(board))
            print()
        outcome = check_winner(board)
        if outcome is not None:
            if verbose:
                print(f"Result: {outcome}")
            return outcome
        player = current_player(board)
        if player == human_plays:
            move = human_player_input(board)
        else:
            move = ai_player_random(board)
            if verbose:
                print(f"  {player} (random AI) plays {move}")
        board = apply_move(board, move, player)

def main() -> None:
    """Entry point. Default: AI vs AI smoke run, prints the result.

    To play interactively, replace this with @play_one_game(human_plays='X').
    """
    play_one_game(human_plays=None, verbose=True)


if __name__ == '__main__':
    main()
