# Compiled from slate doc: test_units
# Generated by slate-code; do not edit by hand.

@pytest.mark.skipif(not os.path.exists(COMPILED), reason="tic_tac_toe.py not yet compiled (issue #28)")
def test_compiled_file_imports():
    spec = importlib.util.spec_from_file_location("tic_tac_toe", COMPILED)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    assert hasattr(module, "BoardState")
    assert hasattr(module, "play_loop")
