import { CARD_TYPE_CODE } from './cards.js';

const PY_KEYWORDS = new Set([
    'False','None','True','and','as','assert','async','await','break','class','continue',
    'def','del','elif','else','except','finally','for','from','global','if','import','in',
    'is','lambda','nonlocal','not','or','pass','raise','return','try','while','with','yield'
]);

const IDENT_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;

export function isValidPythonIdentifier(name) {
    if (!name || !IDENT_RE.test(name)) return false;
    if (PY_KEYWORDS.has(name)) return false;
    return true;
}

export function sanitizeDocFilename(title) {
    // Doc titles are already snake_case via sanitizeTitle. Re-validate and fall back.
    const trimmed = String(title || '').trim();
    if (isValidPythonIdentifier(trimmed)) return trimmed;
    const cleaned = trimmed.toLowerCase().replace(/[^a-z0-9_]/g, '_').replace(/^_+|_+$/g, '');
    if (cleaned && /^[a-z_]/.test(cleaned)) return cleaned;
    return `doc_${cleaned || 'untitled'}`;
}

/**
 * Walk a card's prompt for @references and resolve them to (doc, card) tuples
 * limited to other code cards in the project.
 */
function collectCrossDocImports(card, doc, project) {
    const refs = card.links || [];
    const out = []; // [{ docTitle, cardTitle }]
    if (!project || !refs.length) return out;
    const allDocs = project.getAllDocs ? project.getAllDocs() : [];

    refs.forEach(refTitle => {
        for (const otherDoc of allDocs) {
            if (otherDoc === doc) continue;
            const found = otherDoc.getAllCards().find(c => c.title === refTitle && c.cardType === CARD_TYPE_CODE);
            if (found) {
                out.push({ docTitle: otherDoc.title, cardTitle: found.title });
                break;
            }
        }
    });
    return out;
}

/**
 * Compile a doc's code cards into a single Python file.
 * Returns { filename, source, warnings } or throws on hard errors.
 */
export function compileDocToPython(doc, project) {
    if (!doc) throw new Error('No document to compile.');
    const codeCards = doc.getAllCards().filter(c => c.cardType === CARD_TYPE_CODE);
    if (codeCards.length === 0) {
        throw new Error(`Document "${doc.title}" has no code cards to compile.`);
    }

    const warnings = [];
    const docName = sanitizeDocFilename(doc.title);
    const filename = `${docName}.py`;

    // Collect imports across cards, deduplicated by (module, name).
    const importMap = new Map(); // key: `${module}|${name}` → { module, name }
    const nameCounts = new Map(); // imported `name` → count, for collision detection.
    codeCards.forEach(card => {
        if (!isValidPythonIdentifier(card.title)) {
            warnings.push(`Card title "${card.title}" is not a valid Python identifier; renaming required before compile.`);
        }
        const refs = collectCrossDocImports(card, doc, project);
        refs.forEach(({ docTitle, cardTitle }) => {
            const refDocName = sanitizeDocFilename(docTitle);
            const key = `${refDocName}|${cardTitle}`;
            if (!importMap.has(key)) {
                importMap.set(key, { module: refDocName, name: cardTitle });
                nameCounts.set(cardTitle, (nameCounts.get(cardTitle) || 0) + 1);
            }
        });
    });

    // Resolve aliases: only namespace when two imports share a name (collision).
    const imports = new Map();
    for (const [key, entry] of importMap.entries()) {
        const collides = (nameCounts.get(entry.name) || 0) > 1;
        const alias = collides ? `${entry.name}_${entry.module}` : entry.name;
        imports.set(key, { ...entry, alias });
    }

    if (warnings.some(w => w.includes('not a valid Python identifier'))) {
        // Hard fail: invalid identifiers would produce broken Python.
        throw new Error(warnings.join('\n'));
    }

    // Build the file.
    const lines = [];
    lines.push(`# Compiled from slate doc: ${doc.title}`);
    lines.push(`# Generated by slate-code; do not edit by hand.`);
    lines.push('');
    if (imports.size > 0) {
        for (const { module, name, alias } of imports.values()) {
            if (alias === name) {
                lines.push(`from ${module} import ${name}`);
            } else {
                lines.push(`from ${module} import ${name} as ${alias}`);
            }
        }
        lines.push('');
    }
    codeCards.forEach((card, idx) => {
        const source = (typeof card.getPythonSource === 'function')
            ? (card.getPythonSource() || '')
            : (card.content || '');
        if (idx > 0) lines.push('');  // blank line between symbols (one extra → two blank lines total)
        lines.push(source);
    });

    // Ensure trailing newline.
    let source = lines.join('\n');
    if (!source.endsWith('\n')) source += '\n';

    return { filename, source, warnings };
}
