/**
 * rehydrate.js — pure helpers shared between the live UI rehydrate
 * (`controllers/card_ctl.js`) and the headless round-trip script
 * (`scripts/slate_roundtrip.js`). Keeping them here means both
 * code paths use the *same* prelude-folding + auto-import filtering
 * rules, so a fixed-point proven by `npm run slate:roundtrip` also
 * holds in the browser / VS Code build.
 *
 * Pure / synchronous / no DOM. See issue #53 (round-trip code edits).
 */
import { sanitizeDocFilename, destinationToModulePrefix } from './code_compile.js';

/**
 * Compute the exact set of `from <module> import <name>` lines the
 * compiler will auto-emit for `targetDoc` based on its cards' @-references.
 *
 * Why we need this:
 *   When rehydrate folds the compiled prelude back into the header card
 *   so user-typed inline imports survive the round-trip, we must NOT
 *   fold the auto-emitted cross-doc imports too — otherwise the next
 *   compile re-hoists them as inline imports AND re-emits them as ref
 *   imports, doubling them.
 *
 * Returns Set<string> of normalized import lines (no leading whitespace).
 */
export function autoRefImportLines(targetDoc, project) {
    const lines = new Set();
    if (!targetDoc || !project) return lines;
    const docBase = (d) => {
        const base = sanitizeDocFilename(d.title);
        const prefix = destinationToModulePrefix(d.destination);
        return prefix ? `${prefix}.${base}` : base;
    };
    for (const card of targetDoc.getAllCards()) {
        for (const refTitle of (card.links || [])) {
            for (const otherDoc of project.getAllDocs()) {
                if (otherDoc === targetDoc) continue;
                const found = otherDoc.getAllCards().find(c => c.title === refTitle);
                if (found) {
                    lines.add(`from ${docBase(otherDoc)} import ${found.title}`);
                    break;
                }
            }
        }
    }
    return lines;
}

/**
 * Strip the auto-generated `# Compiled from slate doc:` /
 * `# Generated by slate-code` banner AND the auto-emitted cross-doc
 * import lines from the prelude. Everything else (user-typed inline
 * imports, multi-symbol imports, blank separators, comments) is
 * preserved verbatim and re-folded into the header card so the next
 * compile output is byte-identical.
 */
export function preludeForHeader(preludeBody, autoImports) {
    if (!preludeBody) return '';
    const out = [];
    for (const line of preludeBody.split('\n')) {
        const t = line.trim();
        if (t.startsWith('# Compiled from slate doc:')) continue;
        if (t.startsWith('# Generated by slate-code')) continue;
        if (autoImports && autoImports.has(t)) continue;
        out.push(line);
    }
    let s = 0;
    while (s < out.length && out[s].trim() === '') s++;
    let e = out.length;
    while (e > s && out[e - 1].trim() === '') e--;
    return out.slice(s, e).join('\n');
}
